# primary ADO pipeline
# primary ADO pipeline
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

stages:
  - stage: Init
    jobs:
      - job: Init
        displayName: "Init"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - script: |
              pwd
              ls -al
              echo "Init Done"
