# primary ADO pipeline
# primary ADO pipeline
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

variables:
  TF_CLOUD_ORGANIZATION: CaCloudStudio
  TF_WORKSPACE: Infra
  TF_DIR: terraform

stages:
  - stage: CloneInfraRepo
    displayName: "Clone Infrastructure Repo"
    jobs:
      - job: CloneInfra
        displayName: "Clone Infra Repo"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self

          - script: |
              echo "Repository checked out successfully."
              echo "DEBUG 100"
              ls -al
            displayName: "Success Message"
  - stage: Terraform
    jobs:
      - job: TerraformCI
        displayName: "Terraform Plan and Apply"
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - script: |
              curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
              unzip terraform.zip
              mkdir -p $HOME/bin
              mv terraform $HOME/bin/
              echo 'export PATH=$HOME/bin:$PATH' >> $BASH_ENV
              terraform --version
            displayName: "Install Terraform"

          - script: |
              terraform init
              terraform plan -input=false
            displayName: "Run Terraform"
