- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Configure nginx site
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/cacloudstudio-web
  notify: Reload NGINX

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/cacloudstudio-web
    dest: /etc/nginx/sites-enabled/cacloudstudio-web
    state: link
    force: true

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent