trigger:
  branches:
    - main
  paths:
    include:
      - ansible/**

variables:
  ANSIBLE_DIR: ansible/web

stages:
  - stage: Ansible
    jobs:
      - job: Azure Connection
        displayName: "Export Azure VM information as environment variables"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "ADO Pipeline Connection"
              KeyVaultName: web-cacloud-keyvault # Hard-coded kv name. Can change to variable in future? Depends on Terraform tfvars file, as the names of key vaults are dependent on map names in azure_key_vault
              RunAsPreJob: true

          - script: |
              echo "Setting keyvault password as variable"
              echo "##vso[task.setvariable variable=AZURE_VM_PASSWORD;isOutput=true]$kv-secret
            displayName: "Set VM Password"

          # TODO: Pull Azure VM IP from AzureCLI? task

          - script: echo "##vso[task.setvariable variable=AZURE_VM_IP;isOutput=true]$vm-ip
            displayName: "Set VM IP"

      - job: AnsibleRun
        displayName: "Run Ansible Playbook"
        dependsOn: Azure Connection
        steps:
          - script: |
              cd ..
              sudo apt-get update
              sudo apt-get install -y sshpass python3-pip
              pip3 install ansible
            displayName: "Install Ansible and sshpass"

          - script: |
              cd $(ANSIBLE_DIR)
              export ANSIBLE_HOST_KEY_CHECKING=False
              ansible-playbook -i inventory.yml playbook.yml
            displayName: "Run Ansible Playbook"
            env:
              AZURE_VM_IP: $(AZURE_VM_IP)
              AZURE_VM_ADMINUSER: $(AZURE_VM_ADMINUSER)
              AZURE_VM_PASSWORD: $(AZURE_VM_PASSWORD)
              PYTHON_PATH: $(PYTHON_PATH)
