- name: Install curl and Node.js
  apt:
    name:
      - curl
    state: present
    update_cache: yes

- name: Add Node.js 18.x repo
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  args:
    executable: /bin/bash

- name: Install Node.js
  apt:
    name: nodejs
    state: present

