- name: Install Certbot
  apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present

- name: Obtain Let's Encrypt cert
  shell: |
    certbot --nginx --non-interactive --agree-tos \
    -m {{ email }} -d {{ domain }} -d www.{{ domain }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}