---
- name: Deploy React App on Azure VM with NGINX and HTTPS
  hosts: web
  become: true
  vars:
    domain: "{{ lookup('env', 'DOMAIN') }}"
    email: "{{ lookup('env', 'EMAIL') }}"  
  roles:
    - node
    - app
    - nginx
    - certbot